### PR TITLE
EMG input for visualization

### PR DESCRIPTION
**Pull request by Rvs94**
As requested by Erik, input for EMG visualization.

### CODE REVIEW

**Comment by aremazeilles** [comment]
It would have been great to add the file used for the processing as well. I'll work on it, but I would have earned time if you would have done it

**Comment by aremazeilles** [comment]
So I added the file Erik provided me to process the emg file

Apparently it requires also the gaitEvent file as input. After first attempt, it seems joint_data is also required.

So I adjusted the code, to make it compatible with the rest, but then I get:

```term
run_pi_emg test/input/subject_00_cond_5_run_01_emg.csv test/input/subject_00_cond_5_run_00_gaitEvents.yaml test/input/subject_00_cond_5_run_00_jointAngles.csv out
Traceback (most recent call last):
  File "/home/anthony/code/eurobench/rrd/venv/bin/run_pi_emg", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/anthony/code/eurobench/rrd/src/pi_walk_slope/script/run_pi_emg", line 63, in <module>
    sys.exit(main(fn_emg, fn_gait, fn_joint, folder_out))
  File "/home/anthony/code/eurobench/rrd/src/pi_walk_slope/pi_walk_slope/emg_process.py", line 108, in main
    visualize_emg_run(emg_data, joint_data, gait_events)
  File "/home/anthony/code/eurobench/rrd/src/pi_walk_slope/pi_walk_slope/emg_process.py", line 89, in visualize_emg_run
    emg = emg_envelope(np.array(emg_data[muscle+'_'+side])[r])
IndexError: index 3942 is out of bounds for axis 0 with size 3942
```
Could you revise the code?

Also normally, we expect to generate some PI score. Right now, the code would only display an image. Could you check with Erik whether some metric can be extracted from the emg file?

**Comment by aremazeilles** [comment]
No figure is stored. I'll work on this, and ask you to validate it...

**Comment by aremazeilles** [comment]
The image you inserted:
pi_emg_visualization

The one I get generated and stored:

emg

Could you verify if the one I get is correct?

**Comment by Rvs94** [comment]
Which run/trial did you use? In essence the image looks fine.

**Comment by aremazeilles** [comment]
I used the reference file present within the folder: have a look at the [readme](https://github.com/eurobench/rrd_pi_slope/tree/Rvs94-emg_viz#usage):

```
run_pi_emg test/input/subject_00_cond_5_run_01_emg.csv test/input/subject_00_cond_5_run_00_gaitEvents.yaml out
```

**Comment by Rvs94** [comment]
My bad, there was a mismatch between run numbers, I have updated the EMG file. Output should now match my uploaded image.

**Comment by aremazeilles** [comment]
Ready to merge. Thanks

**Pull request merged**
